### PR TITLE
[core] alt hopac values

### PR DESCRIPTION
**Pull request by haf**

### CODE REVIEW

**Comment by paavohuhtala** [comment]
(Indirectly) merged in d68ad23635492966fd717179b66309a2faa70071.

**Comment by haf** [comment]
Note the branch; WIP, so it's currently hanging inside Logger.log on synchronising on the Alt returned; Hopac warns that I'm running a synchronous operation inside a job. You may choose to pick stuff from this commit, but it's not done yet.

**Comment by paavohuhtala** [comment]
Oh okay, I didn't see the branch before merging, so I merged it anyway (and found the hang while testing). I'll reopen this PR and merge again when it's ready to be merged.

**Comment by haf** [comment]
Thanks.

**Pull request merged**
